version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
    - 15.0.1
  - dependency-name: firebase-admin
    versions:
    - 9.6.0
    - 9.7.0
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.11.0
    - 0.11.1
    - 0.11.10
    - 0.11.11
    - 0.11.12
    - 0.11.13
    - 0.11.14
    - 0.11.15
    - 0.11.2
    - 0.11.3
    - 0.11.5
    - 0.11.6
    - 0.11.8
    - 0.11.9
    - 0.8.47
    - 0.8.48
    - 0.8.50
    - 0.8.51
    - 0.8.52
    - 0.8.53
    - 0.8.54
    - 0.8.55
    - 0.8.57
    - 0.9.0
    - 0.9.2
    - 0.9.3
    - 0.9.4
    - 0.9.6
    - 0.9.7
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
    - 9.0.11
    - 9.0.7
    - 9.0.8
    - 9.0.9
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: "@narumincho/html"
    versions:
    - 0.2.1
    - 0.2.2
    - 0.2.3
    - 0.2.4
    - 0.2.5
  - dependency-name: firebase-functions
    versions:
    - 3.13.2
