name: Deploy to Firebase Hosting

on: workflow_dispatch

jobs:
  type-check-and-build-test:
    name: build test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install npm dependencies (npm ci)
        run: npm ci
      - name: Run Production Build Script
        run: npm run production-build
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: narumincho-creative-record
