name: build and deploy functions

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@master
      - name: Install npm dependencies (npm ci)
        run: npm ci
      - name: Transpile TypeScript (npx tsc)
        run: npx tsc --project ./source/tsconfig.json
      - name: Run Build Script
        run: node ./jsOutDir/index.js
      - name: deploy functions to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: narumincho-homepage
