name: build test

on:
  pull_request:
    branches:
      - renewal

jobs:
  type-check-and-build-test:
    name: build test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install npm dependencies (npm ci)
        run: npm ci
      - name: type check
        run: tsc --project source/tsconfig.json
      - name: Build a docker image
        run: docker build . -t a
