name: build test

on:
  pull_request:
    branches:
      - renewal

jobs:
  type-check-and-build-test:
    name: build test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        run: cargo build --release
